Repository Recc-reborn/recc-server, pull requests merged in 2023-01, with the labels that each got.

#18 [RECC-84]: Tag and songs fetching
  Makefile
  app/Console/Commands/CloneLastFMArtists.php
  app/Http/Controllers/TagController.php
  app/Models/Artist.php
  app/Models/Tag.php
  app/Models/Track.php
  app/Services/LastFMService.php
  database/factories/TagFactory.php
  database/factories/TrackFactory.php
  database/migrations/2022_12_30_233202_create_tags_table.php
  database/migrations/2023_01_06_052342_create_tracks_table.php
  database/migrations/2023_01_06_053744_add_album_to_tracks_table.php
  database/migrations/2023_01_06_055015_add_album_art_url_and_url_to_tracks_table.php
  database/migrations/2023_01_06_122208_create_playlists_table.php
  database/migrations/2023_01_06_214549_create_playbacks_table.php
  database/seeders/TagSeeder.php
Labels: enhancement

#20 Fetching data works at 100% now
  app/Console/Commands/CloneLastFMArtists.php
  database/migrations/2023_01_06_055015_add_album_art_url_and_url_to_tracks_table.php
Labels: bug, enhancement

#19 tracks get fetched correctly
  app/Console/Commands/CloneLastFMArtists.php
  database/factories/TrackFactory.php
  database/migrations/2023_01_06_055015_add_album_art_url_and_url_to_tracks_table.php
Labels: bug

#23 Implemented searchable tracks and paginated searchable artists
  app/Console/Commands/CloneLastFMArtists.php
  app/Http/Controllers/ArtistController.php
  app/Http/Controllers/TrackController.php
  app/Models/Track.php
Labels: enhancement
